### ISSUE TITLE
Invalid floating point operation when calling mpv_create()

### ISSUE THREAD

**Issue by BazzaCuda** [nbuyer/LibMPVDelphi#3]
Hi Edward.

I get my builds of libmpv-2.dll from https://sourceforge.net/projects/mpv-player-windows/files/libmpv/.
These have been working great with LibMPVDelphi for months now.
I specifically use the v3 build for higher-spec machines but either flavor (v3 or non-v3) works with LibMPVDelphi.

With the lastest builds of libmpv-2.dll though, the call to mpv_create in MPVBasePlayer.pas (initPlayer) now generates an "Invalid floating point operation".

The build of libmpv-2.dll from 2023/09/17 works - any build after that date fails.

I don't know anywhere near enough C to begin investigating why this is, so I thought I would raise it with you in the hopes that you're able to.

Kind regards,
Baz.

**Comment by nbuyer** [comment]
Hi,
I downloaded the 64bit version DLL from the link you provided and tested it using MPV_DYNAMIC_LOAD.
The DLL failed to be loaded using LoadLibrary() (error FLOAT_INVALID_OPERATION), which is the standard Windows API.

It seems the DLL is invalid or something wrong in its initialization code and I don't know how to fix it. Please use a previous version of DLL.

Thanks.

**Comment by BazzaCuda** [comment]
Thanks, I'll raise the issue with mpv devs.
Can I ask where you typically get your builds of libmpv from?

**Comment by nbuyer** [comment]
I tried to download the latest libmpv-2.dll (build 20231105) today from:
https://sourceforge.net/projects/mpv-player-windows/files/libmpv/

None of these DLLs could be loaded correctly using LoadLibrary() or calling mpv_create().

The last version that can be directly used is build 20230917.

I could compile the latest libmpv-2.dll (0.36.0) using msys64 through this doc:
https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md
And the output DLLs could be loaded correctly.

Anybody could teach me how to use GCC to build libmpv into one large DLL instead of many small DLLs? TIA
